"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Retailer={id:string;legal_name:string;trade_name:string;tax_id:string;contact_email?:string;phone?:string;status:string;member_count:number;created_at:string};
type AgencyMember={account_id:string;first_name:string;last_name:string;member_role:"admin"|"counter";email:string;status:string;display_status?:string;last_login_at?:string|null};
type Overview={retailers?:Retailer[];message?:string};
type AgencyDashboard={members?:AgencyMember[];user_capacity?:{active:number;total:number;limit:number};message?:string};

export default function AgenciesAdminPage(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[users,setUsers]=useState("all"),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState<Retailer|null>(null),[members,setMembers]=useState<AgencyMember[]>([]),[capacity,setCapacity]=useState<{active:number;total:number;limit:number}|null>(null),[memberMessage,setMemberMessage]=useState(""),[agencyPage,setAgencyPage]=useState(1),[peoplePage,setPeoplePage]=useState(1);
 useEffect(()=>{fetch("/api/admin/overview",{cache:"no-store"}).then(async r=>{const t=await r.text(),p=t?JSON.parse(t):{};if(!r.ok){if(r.status===401||r.status===403){location.replace("/admin/acceso");return}throw new Error(p.message||"No pudimos cargar las agencias.")}setData(p)}).catch(e=>setError(e.message))},[]);
 const retailers=useMemo(()=>{const q=search.trim().toLowerCase();return(data?.retailers||[]).filter(r=>{const matchSearch=!q||[r.trade_name,r.legal_name,r.tax_id,r.contact_email,r.phone].some(v=>String(v||"").toLowerCase().includes(q));const matchStatus=status==="all"||r.status===status;const matchUsers=users==="all"||(users==="none"?r.member_count===0:users==="with"?r.member_count>0:true);return matchSearch&&matchStatus&&matchUsers})},[data,search,status,users]);
 const activeFilters=(status!=="all"?1:0)+(users!=="all"?1:0);const per=10,pages=Math.max(1,Math.ceil(retailers.length/per)),paged=retailers.slice((agencyPage-1)*per,agencyPage*per);const peoplePages=Math.max(1,Math.ceil(members.length/5)),pagedPeople=members.slice((peoplePage-1)*5,peoplePage*5);
 function resetPages(){setAgencyPage(1)}function clearFilters(){setStatus("all");setUsers("all");setAgencyPage(1)}
 async function selectAgency(a:Retailer){setSelected(a);setMembers([]);setCapacity(null);setMemberMessage("Cargando usuarios…");setPeoplePage(1);try{const r=await fetch(`/api/admin/agencies/${a.id}/users`,{cache:"no-store"}),t=await r.text(),p=t?JSON.parse(t) as AgencyDashboard:{};if(!r.ok)throw new Error(p.message||"No pudimos cargar los usuarios.");setMembers(p.members||[]);setCapacity(p.user_capacity||null);setMemberMessage("")}catch(e){setMemberMessage(e instanceof Error?e.message:"No pudimos cargar los usuarios.")}}
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:"18px 24px",color:"#17223b",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1180,margin:"auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Link href="/admin" style={{color:"#315e7b",textDecoration:"none",fontWeight:800}}>← Administración Rumbo</Link><Link href="/admin/agencias/nueva" style={primary}>+ Nueva agencia</Link></div>
  <header style={{margin:"12px 0"}}><p style={{margin:0,color:"#177f93",fontSize:11,fontWeight:800,textTransform:"uppercase"}}>Agencias minoristas</p><h1 style={{margin:"4px 0",fontSize:32}}>Gestión de agencias</h1></header>{error?<div style={errorBox}>{error}</div>:null}
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:10,flexWrap:"wrap",marginBottom:10}}><div><h2 style={{margin:0,fontSize:18}}>Lista de agencias</h2><p style={{margin:"3px 0 0",color:"#718095",fontSize:12}}>{retailers.length} agencias encontradas · Página {agencyPage} de {pages}</p></div></div>
   <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginBottom:8}}><input value={search} onChange={e=>{setSearch(e.target.value);resetPages()}} placeholder="Buscar agencia, RUC, correo o código…" style={{flex:"1 1 430px",padding:"9px 11px",border:"1px solid #cfd6df",borderRadius:7}}/><button onClick={()=>setFiltersOpen(v=>!v)} style={filterButton}>⚙ Filtros{activeFilters?` (${activeFilters})`:""}</button><Link href="/admin/agencias/nueva" style={primary}>+ Nueva agencia</Link></div>
   {filtersOpen?<div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap",padding:10,background:"#f8fafc",border:"1px solid #e3e8ef",borderRadius:8,marginBottom:8}}><label style={label}>Estado<select value={status} onChange={e=>{setStatus(e.target.value);resetPages()}} style={select}><option value="all">Todas</option><option value="active">Activas</option><option value="inactive">Inactivas</option><option value="suspended">Suspendidas</option><option value="pending">Pendientes</option></select></label><label style={label}>Usuarios<select value={users} onChange={e=>{setUsers(e.target.value);resetPages()}} style={select}><option value="all">Todos</option><option value="with">Con usuarios</option><option value="none">Sin usuarios</option></select></label><button onClick={clearFilters} style={clearButton}>Limpiar filtros</button></div>:null}
   {activeFilters?<div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap",marginBottom:8}}>{status!=="all"?<button onClick={()=>{setStatus("all");resetPages()}} style={chip}>Estado: {status} ×</button>:null}{users!=="all"?<button onClick={()=>{setUsers("all");resetPages()}} style={chip}>{users==="with"?"Con usuarios":"Sin usuarios"} ×</button>:null}<button onClick={clearFilters} style={{...clearButton,border:0}}>Limpiar</button></div>:null}
   <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr>{["Agencia","RUC","Contacto","Usuarios","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{paged.map(r=><tr key={r.id} onClick={()=>selectAgency(r)} style={{cursor:"pointer",background:selected?.id===r.id?"#eef5fb":"transparent"}}><td style={td}><b>{r.trade_name}</b><small style={small}>{r.legal_name}</small></td><td style={td}>{r.tax_id}</td><td style={td}>{r.contact_email||"—"}<small style={small}>{r.phone||""}</small></td><td style={td}>{r.member_count}</td><td style={td}><span style={pill}>{r.status}</span></td></tr>)}</tbody></table>{!paged.length?<p style={{color:"#718095"}}>No encontramos agencias con esos criterios.</p>:null}</div><div style={pager}><button disabled={agencyPage<=1} onClick={()=>setAgencyPage(p=>p-1)}>‹ Anterior</button><button disabled={agencyPage>=pages} onClick={()=>setAgencyPage(p=>p+1)}>Siguiente ›</button></div>
  </section>
  <section style={{...card,marginTop:14,minHeight:240}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><p style={{margin:0,color:"#177f93",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Personas</p><h2 style={{margin:"4px 0"}}>{selected?selected.trade_name:"Selecciona una agencia"}</h2></div>{selected?<div style={{display:"flex",gap:8,alignItems:"center"}}>{capacity?<span style={pill}>{capacity.active}/{capacity.limit} activos</span>:null}<Link href={`/admin/agencias/personas/nueva?retailer=${selected.id}`} style={primary}>+ Nueva persona</Link></div>:null}</div>{memberMessage?<p>{memberMessage}</p>:null}{selected&&!memberMessage?<><div style={{overflowX:"auto",marginTop:10}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Usuario","Rol","Correo","Último inicio","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{pagedPeople.map(m=><tr key={m.account_id}><td style={td}><b>{m.first_name} {m.last_name}</b></td><td style={td}>{m.member_role==="admin"?"Administrador":"Counter"}</td><td style={td}>{m.email}</td><td style={td}>{m.last_login_at?new Date(m.last_login_at).toLocaleString("es-PE"):"Nunca"}</td><td style={td}>{m.display_status||m.status}</td></tr>)}</tbody></table></div><div style={pager}><span>{members.length} personas · 5 por página</span><button disabled={peoplePage<=1} onClick={()=>setPeoplePage(p=>p-1)}>‹ Anterior</button><button disabled={peoplePage>=peoplePages} onClick={()=>setPeoplePage(p=>p+1)}>Siguiente ›</button></div></>:null}</section>
 </div></main>
}
const card:React.CSSProperties={background:"white",border:"1px solid #e1e6ec",borderRadius:12,padding:15};const th:React.CSSProperties={textAlign:"left",padding:"7px 9px",border:"1px solid #dfe4ea",background:"#eef2f5",fontSize:10,textTransform:"uppercase"};const td:React.CSSProperties={padding:"7px 9px",border:"1px solid #e3e7eb",fontSize:12};const small:React.CSSProperties={display:"block",color:"#7d8796",fontSize:10};const pill:React.CSSProperties={padding:"4px 7px",borderRadius:999,background:"#eef3f7",fontWeight:800,fontSize:10};const primary:React.CSSProperties={background:"#102b50",color:"white",padding:"8px 11px",borderRadius:7,textDecoration:"none",fontWeight:800,fontSize:12};const filterButton:React.CSSProperties={padding:"9px 12px",border:"1px solid #cfd6df",borderRadius:7,background:"white",fontWeight:800,color:"#344054",cursor:"pointer"};const clearButton:React.CSSProperties={padding:"8px 10px",border:"1px solid #d7dde5",borderRadius:7,background:"white",color:"#526071",cursor:"pointer"};const chip:React.CSSProperties={padding:"5px 8px",border:"1px solid #cbd5e1",borderRadius:999,background:"#eef4f8",fontSize:11,cursor:"pointer"};const label:React.CSSProperties={display:"grid",gap:4,fontSize:11,color:"#526071"};const select:React.CSSProperties={padding:"7px 9px",border:"1px solid #cfd6df",borderRadius:7,background:"white",minWidth:150};const pager:React.CSSProperties={display:"flex",justifyContent:"flex-end",gap:8,alignItems:"center",marginTop:9,fontSize:12,color:"#718095"};const errorBox:React.CSSProperties={padding:10,background:"#fff5f5",color:"#991b1b",border:"1px solid #fecaca",borderRadius:8,marginBottom:10};