"use client";

import Link from "next/link";
import { useState } from "react";

export default function NewPartnerPage(){
  const [form,setForm]=useState({first_name:"",last_name:"",email:"",document_type:"DNI",document_number:"",phone:""});
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [credentials,setCredentials]=useState<{username:string;temporary_password:string}|null>(null);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const response=await fetch('/api/admin/partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.message||'No pudimos crear el Partner.');setCredentials(payload.credentials);setMessage('Partner creado correctamente.');}catch(e){setMessage(e instanceof Error?e.message:'No pudimos crear el Partner.')}finally{setBusy(false)}}
  return <main style={{minHeight:'100vh',background:'#f5f7fa',padding:24,color:'#17233b'}}><div style={{maxWidth:900,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><p style={eyebrow}>Partners</p><h1 style={{margin:'4px 0'}}>Nuevo Partner</h1><p style={muted}>Crea el acceso y el código de referido del Partner.</p></div><Link href="/admin" style={secondary}>← Backoffice</Link></div><form onSubmit={submit} style={card}><div style={grid}><label style={label}>Nombres<input style={input} value={form.first_name} onChange={e=>setForm(v=>({...v,first_name:e.target.value}))} required/></label><label style={label}>Apellidos<input style={input} value={form.last_name} onChange={e=>setForm(v=>({...v,last_name:e.target.value}))} required/></label><label style={label}>Correo<input style={input} type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} required/></label><label style={label}>Tipo documento<select style={input} value={form.document_type} onChange={e=>setForm(v=>({...v,document_type:e.target.value}))}><option>DNI</option><option>CE</option><option>PASSPORT</option><option>RUC</option></select></label><label style={label}>Nro. documento<input style={input} value={form.document_number} onChange={e=>setForm(v=>({...v,document_number:e.target.value}))} required/></label><label style={label}>Teléfono<input style={input} value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/></label></div>{message?<p style={{color:credentials?'#176b45':'#9b2c2c'}}>{message}</p>:null}<button style={primary} disabled={busy}>{busy?'Creando…':'Crear Partner'}</button></form></div>{credentials?<div style={overlay} onClick={()=>setCredentials(null)}><div style={modal} onClick={e=>e.stopPropagation()}><h2>Credenciales iniciales</h2><p style={muted}>Muéstralas o entrégalas al Partner. La contraseña es temporal.</p><div style={credentialBox}><span>Usuario</span><strong>{credentials.username}</strong><span>Contraseña temporal</span><strong>{credentials.temporary_password}</strong></div><button style={primary} onClick={()=>setCredentials(null)}>Entendido</button></div></div>:null}</main>
}
const card:React.CSSProperties={marginTop:18,background:'#fff',border:'1px solid #e1e6ec',borderRadius:14,padding:20};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14};const label:React.CSSProperties={display:'grid',gap:6,fontSize:13,fontWeight:700};const input:React.CSSProperties={padding:'10px 12px',border:'1px solid #d0d5dd',borderRadius:8,fontSize:14};const primary:React.CSSProperties={marginTop:16,border:0,borderRadius:9,background:'#10223f',color:'#fff',padding:'10px 16px',fontWeight:800};const secondary:React.CSSProperties={padding:'9px 12px',border:'1px solid #d0d5dd',borderRadius:9,color:'#17233b',textDecoration:'none',background:'#fff'};const muted:React.CSSProperties={margin:0,color:'#667085'};const eyebrow:React.CSSProperties={margin:0,color:'#e9573b',fontSize:11,fontWeight:800,textTransform:'uppercase',letterSpacing:'.12em'};const overlay:React.CSSProperties={position:'fixed',inset:0,background:'rgba(15,23,42,.55)',display:'grid',placeItems:'center',zIndex:100};const modal:React.CSSProperties={width:'min(500px,calc(100vw - 32px))',background:'#fff',borderRadius:16,padding:24,boxShadow:'0 25px 70px rgba(0,0,0,.25)'};const credentialBox:React.CSSProperties={display:'grid',gap:6,background:'#f7f8fa',border:'1px solid #e4e7ec',borderRadius:10,padding:14,marginTop:16};
