"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type User={account_id:string;first_name:string;last_name:string;internal_role:"admin"|"counter";email:string;status:string;job_title?:string|null;last_login_at?:string|null};
type Credentials={username:string;temporary_password:string;must_change_password:boolean};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};
const th:React.CSSProperties={textAlign:"left",padding:"7px 9px",border:"1px solid #dfe4ea",background:"#eef2f5",color:"#536273",fontSize:10,fontWeight:800,textTransform:"uppercase"};
const td:React.CSSProperties={padding:"7px 9px",border:"1px solid #e3e7eb",fontSize:12,verticalAlign:"middle"};
const primary:React.CSSProperties={background:"#10223f",color:"white",padding:"8px 11px",borderRadius:8,textDecoration:"none",fontWeight:800,fontSize:12,border:0,cursor:"pointer"};

export default function RumboUsersPage(){
  const [users,setUsers]=useState<User[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null),[showForm,setShowForm]=useState(false),[page,setPage]=useState(1);
  async function load(){const r=await fetch("/api/admin/user-management",{cache:"no-store"});const p=await r.json();if(!r.ok){if(r.status===401||r.status===403)location.replace("/admin/acceso");throw new Error(p.message||"No pudimos cargar usuarios.")}setUsers(p.users||[])}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/user-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"internal_user",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear el usuario.");else{setCredentials(p.credentials);setShowForm(false);await load()}setBusy(false)}
  const perPage=10,pages=Math.max(1,Math.ceil(users.length/perPage)),rows=useMemo(()=>users.slice((page-1)*perPage,page*perPage),[users,page]);
  return <main style={{minHeight:"100vh",background:"#f6f7f9",padding:"18px 24px",color:"#17233b"}}><div style={{maxWidth:1180,margin:"auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:12}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Rumbo · Administración mayorista</p><h1 style={{margin:"4px 0 0",fontSize:32}}>Usuarios Rumbo</h1><p style={{margin:"5px 0 0",color:"#667085",fontSize:12}}>Usuarios internos · 10 por página.</p></div><div style={{display:"flex",gap:8}}><Link href="/admin" style={{...primary,background:"white",color:"#344054",border:"1px solid #d0d5dd"}}>← Backoffice</Link><button style={primary} onClick={()=>setShowForm(true)}>+ Nuevo usuario</button></div></div>
    {error?<div style={{marginTop:12,padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8}}>{error}</div>:null}
    <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15,marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:9}}><h2 style={{margin:0,fontSize:17}}>Personas internas</h2><span style={{fontSize:12,color:"#667085"}}>Página {page} de {pages}</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12,minWidth:850}}><thead><tr>{["Nombre","Correo","Rol","Cargo","Último ingreso","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(u=><tr key={u.account_id}><td style={td}><b>{u.first_name} {u.last_name}</b></td><td style={td}>{u.email}</td><td style={td}>{u.internal_role==="admin"?"Administrador":"Counter"}</td><td style={td}>{u.job_title||"—"}</td><td style={td}>{u.last_login_at?new Date(u.last_login_at).toLocaleString("es-PE"):"Nunca"}</td><td style={td}>{u.status}</td></tr>)}</tbody></table></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,alignItems:"center",marginTop:9,fontSize:12,color:"#667085"}}><span>{users.length} usuarios</span><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>‹ Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Siguiente ›</button></div></section>
    {showForm?<div onClick={()=>setShowForm(false)} style={{position:"fixed",inset:0,background:"rgba(16,24,40,.55)",display:"grid",placeItems:"center",zIndex:1000,padding:20}}><form onSubmit={submit} onClick={e=>e.stopPropagation()} style={{width:"min(620px,100%)",background:"white",borderRadius:14,padding:20,boxShadow:"0 24px 80px rgba(0,0,0,.28)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{margin:0}}>Nuevo usuario Rumbo</h2><button type="button" onClick={()=>setShowForm(false)} style={{border:0,background:"transparent",fontSize:22}}>×</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14}}><label style={label}>Nombres<input name="first_name" required style={field}/></label><label style={label}>Apellidos<input name="last_name" required style={field}/></label><label style={label}>Correo<input name="email" type="email" required style={field}/></label><label style={label}>Rol<select name="role" defaultValue="counter" style={field}><option value="counter">Counter Rumbo</option><option value="admin">Administrador Rumbo</option></select></label><label style={label}>Cargo<input name="job_title" placeholder="Gerente / Ejecutivo / Counter" style={field}/></label><label style={label}>Teléfono<input name="phone" style={field}/></label></div><button disabled={busy} style={{...primary,marginTop:14}}>{busy?"Creando…":"Crear usuario"}</button></form></div>:null}
    {credentials?<div onClick={()=>setCredentials(null)} style={{position:"fixed",inset:0,background:"rgba(16,24,40,.55)",display:"grid",placeItems:"center",zIndex:1100,padding:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(480px,100%)",background:"white",borderRadius:14,padding:20}}><h2 style={{marginTop:0}}>Usuario creado</h2><p style={{color:"#667085"}}>Entrega estas credenciales una sola vez.</p><div style={{background:"#f8fafc",padding:14,borderRadius:10}}><small>Usuario</small><b style={{display:"block",fontSize:17}}>{credentials.username}</b><small style={{display:"block",marginTop:10}}>Contraseña temporal</small><b style={{display:"block",fontSize:20}}>{credentials.temporary_password}</b></div><button onClick={()=>setCredentials(null)} style={{...primary,marginTop:14}}>Entendido</button></div></div>:null}
  </div></main>
}
