"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type User={account_id:string;first_name:string;last_name:string;internal_role:"admin"|"counter";email:string;status:string;job_title?:string|null;last_login_at?:string|null};
type Credentials={username:string;temporary_password:string;must_change_password:boolean};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};

export default function RumboUsersPage(){
  const [users,setUsers]=useState<User[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null);
  async function load(){const r=await fetch("/api/admin/user-management",{cache:"no-store"});const p=await r.json();if(!r.ok){if(r.status===401||r.status===403)location.replace("/admin/acceso");throw new Error(p.message||"No pudimos cargar usuarios.")}setUsers(p.users||[])}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/user-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"internal_user",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear el usuario.");else{setCredentials(p.credentials);e.currentTarget.reset();await load()}setBusy(false)}
  return <main style={{minHeight:"100vh",background:"#f6f7f9",padding:"18px 24px",color:"#17233b"}}><div style={{maxWidth:1180,margin:"auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Rumbo · Administración</p><h1 style={{margin:"4px 0 0"}}>Usuarios Rumbo</h1></div><Link href="/admin" style={{textDecoration:"none",color:"#344054"}}>← Backoffice</Link></div>
    {error?<div style={{marginTop:12,padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8}}>{error}</div>:null}
    <section style={{display:"grid",gridTemplateColumns:"360px 1fr",gap:12,marginTop:14,alignItems:"start"}}>
      <form onSubmit={submit} style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15}}><h2 style={{margin:"0 0 10px",fontSize:17}}>Nuevo usuario</h2><div style={{display:"grid",gap:9}}><label style={label}>Nombres<input name="first_name" required style={field}/></label><label style={label}>Apellidos<input name="last_name" required style={field}/></label><label style={label}>Correo<input name="email" type="email" required style={field}/></label><label style={label}>Rol<select name="role" defaultValue="counter" style={field}><option value="counter">Counter Rumbo</option><option value="admin">Administrador Rumbo</option></select></label><label style={label}>Cargo<input name="job_title" placeholder="Gerente / Ejecutivo / Counter" style={field}/></label><label style={label}>Teléfono<input name="phone" style={field}/></label></div><button disabled={busy} style={{marginTop:11,border:0,borderRadius:8,padding:"9px 13px",background:"#10223f",color:"white",fontWeight:800}}>{busy?"Creando…":"Crear usuario"}</button></form>
      <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15}}><h2 style={{margin:"0 0 10px",fontSize:17}}>Personas internas</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Nombre","Correo","Rol","Cargo","Último ingreso","Estado"].map(h=><th key={h} style={{padding:"7px",borderBottom:"1px solid #e4e7ec",textAlign:"left",fontSize:10,color:"#667085"}}>{h}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.account_id}><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}><b>{u.first_name} {u.last_name}</b></td><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}>{u.email}</td><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}>{u.internal_role==="admin"?"Administrador":"Counter"}</td><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}>{u.job_title||"—"}</td><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}>{u.last_login_at?new Date(u.last_login_at).toLocaleString("es-PE"):"Nunca"}</td><td style={{padding:7,borderBottom:"1px solid #eef0f3"}}>{u.status}</td></tr>)}</tbody></table></div></section>
    </section>
    {credentials?<div onClick={()=>setCredentials(null)} style={{position:"fixed",inset:0,background:"rgba(16,24,40,.55)",display:"grid",placeItems:"center",zIndex:1000,padding:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(480px,100%)",background:"white",borderRadius:14,padding:20,boxShadow:"0 24px 80px rgba(0,0,0,.28)"}}><h2 style={{marginTop:0}}>Usuario creado</h2><p style={{color:"#667085"}}>Entrega estas credenciales una sola vez. La contraseña deberá cambiarse en el primer ingreso.</p><div style={{background:"#f8fafc",padding:14,borderRadius:10}}><small>Usuario</small><b style={{display:"block",fontSize:17}}>{credentials.username}</b><small style={{display:"block",marginTop:10}}>Contraseña temporal</small><b style={{display:"block",fontSize:20,letterSpacing:.5}}>{credentials.temporary_password}</b></div><button onClick={()=>setCredentials(null)} style={{marginTop:14,border:0,borderRadius:8,padding:"9px 13px",background:"#10223f",color:"white",fontWeight:800}}>Entendido</button></div></div>:null}
  </div></main>
}
