"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Departure={id:string;origin_iata?:string|null;departure_date?:string|null;return_date?:string|null;currency:string;price_amount:number;cost_amount?:number|null;margin_amount?:number|null;margin_pct?:number|null;capacity?:number|null;available_capacity?:number|null;status:string};
type Product={id:string;slug:string;name:string;country?:string|null;city?:string|null;destination_iata?:string|null;product_type?:string|null;provider?:string|null;duration_label?:string|null;tag?:string|null;status:string;featured?:boolean;from_price_amount?:number|null;active_departure_count?:number;departures?:Departure[];currency?:string|null;price_amount?:number|null;cost_amount?:number|null;margin_amount?:number|null;margin_pct?:number|null;available_capacity?:number|null;image_url?:string|null};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};
const th:React.CSSProperties={textAlign:"left",padding:"7px 9px",border:"1px solid #dfe4ea",background:"#eef2f5",fontSize:10,textTransform:"uppercase",color:"#536273"};
const td:React.CSSProperties={padding:"7px 9px",border:"1px solid #e3e7eb",fontSize:12,verticalAlign:"middle"};
const primary:React.CSSProperties={background:"#102b50",color:"white",padding:"9px 12px",borderRadius:8,border:0,fontWeight:800,cursor:"pointer"};

export default function CatalogPanel(){
 const [products,setProducts]=useState<Product[]>([]),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[provider,setProvider]=useState("all"),[page,setPage]=useState(1),[selected,setSelected]=useState<Product|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/catalog",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.message||"No pudimos cargar el catálogo.");setProducts(p.products||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const providers=useMemo(()=>Array.from(new Set(products.map(p=>p.provider).filter(Boolean))) as string[],[products]);
 const rows=useMemo(()=>{const q=search.trim().toLowerCase();return products.filter(p=>(!q||[p.name,p.slug,p.city,p.country,p.destination_iata,p.provider,p.tag].some(v=>String(v||"").toLowerCase().includes(q)))&&(status==="all"||p.status===status)&&(provider==="all"||p.provider===provider))},[products,search,status,provider]);
 const per=10,pages=Math.max(1,Math.ceil(rows.length/per)),paged=rows.slice((page-1)*per,page*per);
 function money(v?:number|null,c="USD"){return v==null?"—":new Intl.NumberFormat("es-PE",{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(v)}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const f=new FormData(e.currentTarget),body=Object.fromEntries(f.entries());const r=await fetch("/api/admin/catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json();if(!r.ok)throw new Error(p.message||"No pudimos crear el producto.");setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"No pudimos crear el producto.")}finally{setBusy(false)}}
 return <div style={{maxWidth:1400,margin:"0 auto",color:"#17233b"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"end",marginBottom:14}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,letterSpacing:1.2,textTransform:"uppercase"}}>Rumbo · Administración mayorista</p><h1 style={{fontSize:32,margin:"4px 0"}}>Catálogo</h1><p style={{margin:0,color:"#667085"}}>Productos, salidas, precios base, costos, margen y disponibilidad.</p></div><button style={primary} onClick={()=>setOpen(true)}>+ Nuevo producto</button></div>
  {error?<div style={{padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8,marginBottom:10}}>{error}</div>:null}
  <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15}}>
   <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:10}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar producto, destino, proveedor o código…" style={{...field,flex:"1 1 420px"}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} style={{...field,width:170}}><option value="all">Todos los estados</option><option value="published">Publicado</option><option value="draft">Borrador</option><option value="archived">Archivado</option></select><select value={provider} onChange={e=>{setProvider(e.target.value);setPage(1)}} style={{...field,width:180}}><option value="all">Todos los proveedores</option>{providers.map(x=><option key={x}>{x}</option>)}</select></div>
   <div style={{display:"flex",justifyContent:"space-between",fontSize:12,color:"#667085",marginBottom:6}}><span>{rows.length} productos encontrados</span><span>Página {page} de {pages}</span></div>
   <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1050}}><thead><tr>{["Producto","Destino","Proveedor","Salidas","Precio desde","Costo","Margen","Cupos","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{paged.map(p=>{const d=p.departures?.[0];const curr=d?.currency||"USD";return <tr key={p.id} onClick={()=>setSelected(p)} style={{cursor:"pointer",background:selected?.id===p.id?"#eef5fb":"transparent"}}><td style={td}><b>{p.name}</b><small style={{display:"block",color:"#7d8796"}}>{p.slug}</small></td><td style={td}>{[p.city,p.country,p.destination_iata].filter(Boolean).join(" · ")||"—"}</td><td style={td}>{p.provider||"Rumbo"}</td><td style={td}>{p.active_departure_count||0}</td><td style={td}>{money(p.from_price_amount??d?.price_amount,curr)}</td><td style={td}>{money(d?.cost_amount,curr)}</td><td style={td}>{d?.margin_pct!=null?`${d.margin_pct.toFixed(1)}%`:money(d?.margin_amount,curr)}</td><td style={td}>{d?.available_capacity??"—"}</td><td style={td}><span style={{padding:"4px 7px",borderRadius:999,background:"#eef3f7",fontWeight:800,fontSize:10}}>{p.status}</span></td></tr>})}</tbody></table></div>
   <div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:9}}><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>‹ Anterior</button><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>Siguiente ›</button></div>
  </section>
  <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15,marginTop:14,minHeight:180}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Salidas</p><h2 style={{margin:"4px 0"}}>{selected?selected.name:"Selecciona un producto"}</h2></div></div>{selected?<div style={{overflowX:"auto",marginTop:10}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{["Origen","Salida","Retorno","Precio","Costo","Margen","Capacidad","Disponibles","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(selected.departures||[]).map(d=><tr key={d.id}><td style={td}>{d.origin_iata||"—"}</td><td style={td}>{d.departure_date||"—"}</td><td style={td}>{d.return_date||"—"}</td><td style={td}>{money(d.price_amount,d.currency)}</td><td style={td}>{money(d.cost_amount,d.currency)}</td><td style={td}>{d.margin_pct!=null?`${d.margin_pct.toFixed(1)}%`:money(d.margin_amount,d.currency)}</td><td style={td}>{d.capacity??"—"}</td><td style={td}>{d.available_capacity??"—"}</td><td style={td}>{d.status}</td></tr>)}</tbody></table>{!(selected.departures||[]).length?<p style={{color:"#667085"}}>Este producto todavía no tiene salidas.</p>:null}</div>:<p style={{color:"#667085"}}>Haz clic en una fila para ver sus salidas y disponibilidad.</p>}</section>
  {open?<div onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}} style={{position:"fixed",inset:0,zIndex:2000,background:"rgba(15,23,42,.62)",display:"grid",placeItems:"center",padding:20,overflowY:"auto"}}><form onSubmit={create} onMouseDown={e=>e.stopPropagation()} style={{position:"relative",width:"min(900px,100%)",maxHeight:"calc(100vh - 40px)",overflowY:"auto",background:"white",borderRadius:16,padding:22,boxShadow:"0 28px 80px rgba(0,0,0,.3)"}}><button type="button" onClick={()=>setOpen(false)} style={{position:"absolute",right:14,top:10,border:0,background:"transparent",fontSize:28,cursor:"pointer",color:"#667085"}}>×</button><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Catálogo</p><h2 style={{margin:"4px 0"}}>Nuevo producto</h2><p style={{color:"#667085",marginTop:0}}>Crea el producto y, si quieres, su primera salida en el mismo paso.</p><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><L n="name" t="Nombre" req/><L n="slug" t="Código / slug" req/><L n="country" t="País"/><L n="city" t="Ciudad"/><L n="destination_iata" t="IATA destino"/><L n="provider" t="Proveedor" dv="Rumbo"/><L n="duration_label" t="Duración"/><L n="tag" t="Etiqueta"/><label style={label}>Estado<select name="status" defaultValue="draft" style={field}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><L n="image_url" t="URL de imagen"/><L n="origin_iata" t="IATA origen"/><L n="departure_date" t="Fecha salida" type="date"/><L n="return_date" t="Fecha retorno" type="date"/><label style={label}>Moneda<select name="currency" defaultValue="USD" style={field}><option>USD</option><option>PEN</option><option>EUR</option><option>GBP</option></select></label><L n="price_amount" t="Precio base" type="number"/><L n="cost_amount" t="Costo" type="number"/><L n="capacity" t="Capacidad" type="number"/><L n="low_stock_threshold" t="Alerta de pocos cupos" type="number" dv="5"/></div><button disabled={busy} style={{...primary,marginTop:14}}>{busy?"Creando…":"Crear producto"}</button></form></div>:null}
 </div>
}
function L({n,t,type="text",req=false,dv}:{n:string;t:string;type?:string;req?:boolean;dv?:string}){return <label style={label}>{t}<input name={n} type={type} required={req} defaultValue={dv} style={field}/></label>}
