"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Rule={id:string;name:string;effect:"charge"|"discount";calculation_type:"percent"|"fixed_booking"|"fixed_passenger";value:number;currency?:string|null;scope_type:string;scope_value?:string|null;priority:number;is_active:boolean};
type Program={id:string;code:string;name:string;program_type:"campaign"|"season"|"administrative";description?:string;sale_start?:string|null;sale_end?:string|null;travel_start?:string|null;travel_end?:string|null;priority:number;status:string;rules:Rule[]};
type Simulation={currency:string;base_amount:number;travellers:number;delta_amount:number;total_amount:number;applied:Array<{id:string;name:string;program_name?:string;program_type?:string;amount:number;running_total:number}>};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10};
const primary:React.CSSProperties={padding:"9px 13px",border:0,borderRadius:8,background:"#10223f",color:"white",fontWeight:700,cursor:"pointer"};

export default function PricingPanel(){
  const [programs,setPrograms]=useState<Program[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[simulation,setSimulation]=useState<Simulation|null>(null),[selectedProgram,setSelectedProgram]=useState(""),[simulatorOpen,setSimulatorOpen]=useState(false);
  async function load(){const r=await fetch("/api/admin/pricing",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.message||"No pudimos cargar Pricing.");setPrograms(p.programs||[]);if(!selectedProgram&&p.programs?.[0])setSelectedProgram(p.programs[0].id)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submitProgram(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("program");setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"program",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear el programa.");else{e.currentTarget.reset();await load()}setBusy("")}
  async function submitRule(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("rule");setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"rule",...Object.fromEntries(f.entries()),program_id:selectedProgram})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear la regla.");else{e.currentTarget.reset();await load()}setBusy("")}
  async function simulate(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("simulate");setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"simulate",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos simular el precio.");else setSimulation(p);setBusy("")}
  async function toggle(rule:Rule){await fetch("/api/admin/pricing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id,is_active:!rule.is_active})});await load()}
  const rules=useMemo(()=>programs.flatMap(p=>(p.rules||[]).map(r=>({...r,program:p}))),[programs]);
  return <>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:12}}><div><h2 style={{margin:"0 0 4px",fontSize:20}}>Pricing</h2><p style={{margin:0,color:"#667085",fontSize:12}}>Campañas, temporadas y cargos que forman el precio final.</p></div><button onClick={()=>{setSimulation(null);setSimulatorOpen(true)}} style={{...primary,background:"#ff6b4a"}}>Simular precio</button></div>
    {error?<div style={{padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8,marginBottom:12}}>{error}</div>:null}
    <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,alignItems:"start"}}>
      <form onSubmit={submitProgram} style={card}><h3 style={{margin:"0 0 10px",fontSize:17}}>1. Programa comercial</h3><div style={grid}><label style={label}>Tipo<select name="program_type" style={field} defaultValue="campaign"><option value="campaign">Campaña</option><option value="season">Temporada</option><option value="administrative">Cargo administrativo</option></select></label><label style={label}>Código<input name="code" style={field} placeholder="VERANO-2027" required/></label><label style={label}>Nombre<input name="name" style={field} required/></label><label style={label}>Prioridad<input name="priority" type="number" defaultValue="100" style={field}/></label><label style={label}>Venta desde<input name="sale_start" type="date" style={field}/></label><label style={label}>Venta hasta<input name="sale_end" type="date" style={field}/></label><label style={label}>Viaje desde<input name="travel_start" type="date" style={field}/></label><label style={label}>Viaje hasta<input name="travel_end" type="date" style={field}/></label></div><label style={{...label,marginTop:10}}>Descripción<textarea name="description" style={{...field,minHeight:62}}/></label><button disabled={busy==="program"} style={{...primary,marginTop:10}}>{busy==="program"?"Guardando…":"Crear programa"}</button></form>
      <form onSubmit={submitRule} style={card}><h3 style={{margin:"0 0 10px",fontSize:17}}>2. Regla de precio</h3><div style={grid}><label style={label}>Programa<select value={selectedProgram} onChange={e=>setSelectedProgram(e.target.value)} style={field} required>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label style={label}>Nombre<input name="name" style={field} required/></label><label style={label}>Efecto<select name="effect" style={field}><option value="charge">Cargo +</option><option value="discount">Descuento −</option></select></label><label style={label}>Cálculo<select name="calculation_type" style={field}><option value="percent">Porcentaje</option><option value="fixed_booking">Monto fijo por reserva</option><option value="fixed_passenger">Monto fijo por pasajero</option></select></label><label style={label}>Valor<input name="value" type="number" step="0.01" min="0" style={field} required/></label><label style={label}>Moneda<select name="currency" style={field}><option>USD</option><option>PEN</option><option>EUR</option><option>GBP</option></select></label><label style={label}>Ámbito<select name="scope_type" style={field}><option value="all">Todo</option><option value="region">Región</option><option value="destination">Destino</option><option value="product">Producto</option><option value="tag">Etiqueta</option><option value="provider">Proveedor</option></select></label><label style={label}>Valor ámbito<input name="scope_value" style={field}/></label><label style={label}>Prioridad<input name="priority" type="number" defaultValue="100" style={field}/></label></div><button disabled={busy==="rule"||!selectedProgram} style={{...primary,marginTop:10}}>{busy==="rule"?"Guardando…":"Crear regla"}</button></form>
    </section>
    <section style={{...card,marginTop:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h3 style={{margin:"0 0 4px",fontSize:17}}>Reglas activas</h3><p style={{margin:0,color:"#667085",fontSize:12}}>Estas reglas forman el precio cuando sus condiciones coinciden.</p></div></div><div style={{overflowX:"auto",marginTop:8}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Programa","Tipo","Regla","Ámbito","Cálculo","Valor","Prioridad","Estado"].map(h=><th key={h} style={{padding:"8px 7px",borderBottom:"1px solid #e4e7ec",textAlign:"left",fontSize:10,color:"#667085"}}>{h}</th>)}</tr></thead><tbody>{rules.map((x:any)=><tr key={x.id}><td style={cell}>{x.program.name}</td><td style={cell}>{x.program.program_type}</td><td style={cell}><b>{x.name}</b></td><td style={cell}>{x.scope_type}{x.scope_value?` · ${x.scope_value}`:""}</td><td style={cell}>{x.effect} · {x.calculation_type}</td><td style={cell}>{x.value}{x.calculation_type==="percent"?"%":` ${x.currency||""}`}</td><td style={cell}>{x.priority}</td><td style={cell}><button onClick={()=>toggle(x)} style={{border:"1px solid #d0d5dd",background:x.is_active?"#ecfdf3":"#f2f4f7",borderRadius:999,padding:"5px 9px"}}>{x.is_active?"Activa":"Pausada"}</button></td></tr>)}</tbody></table></div></section>
    {simulatorOpen?<div onMouseDown={()=>setSimulatorOpen(false)} style={overlay}><section onMouseDown={e=>e.stopPropagation()} style={modal}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><div><p style={{margin:"0 0 4px",color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Pricing Rumbo</p><h2 style={{margin:0}}>Simular precio</h2></div><button onClick={()=>setSimulatorOpen(false)} style={{border:0,background:"transparent",fontSize:26}}>×</button></div><form onSubmit={simulate} style={{marginTop:14}}><div style={grid}><label style={label}>Precio base<input name="base_amount" type="number" step="0.01" defaultValue="1000" style={field} required/></label><label style={label}>Moneda<select name="currency" style={field}><option>USD</option><option>PEN</option><option>EUR</option><option>GBP</option></select></label><label style={label}>Pasajeros<input name="travellers" type="number" min="1" defaultValue="2" style={field}/></label><label style={label}>Región<input name="region" placeholder="ASIA" style={field}/></label><label style={label}>Destino<input name="destination" placeholder="NRT" style={field}/></label><label style={label}>Etiqueta<input name="tag" placeholder="DISNEY" style={field}/></label><label style={label}>Producto<input name="product" style={field}/></label><label style={label}>Proveedor<input name="provider" style={field}/></label><label style={label}>Fecha venta<input name="sale_date" type="date" style={field}/></label><label style={label}>Fecha viaje<input name="travel_date" type="date" style={field}/></label></div><button disabled={busy==="simulate"} style={{...primary,marginTop:12}}>{busy==="simulate"?"Calculando…":"Calcular precio"}</button></form>{simulation?<div style={{marginTop:16,borderTop:"1px solid #e4e7ec",paddingTop:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}><Result label="Precio base" value={`${simulation.currency} ${simulation.base_amount.toFixed(2)}`}/><Result label="Ajuste" value={`${simulation.currency} ${simulation.delta_amount.toFixed(2)}`}/><Result label="Precio final" value={`${simulation.currency} ${simulation.total_amount.toFixed(2)}`}/></div><h3 style={{margin:"14px 0 6px"}}>Regla aplicada</h3>{simulation.applied?.length?simulation.applied.map(a=><div key={a.id} style={{padding:"8px 10px",border:"1px solid #e4e7ec",borderRadius:8,marginBottom:6}}><b>{a.name}</b><span style={{float:"right"}}>{a.amount>=0?"+":""}{simulation.currency} {a.amount.toFixed(2)}</span><small style={{display:"block",color:"#667085"}}>{a.program_name||"Programa comercial"} · acumulado {simulation.currency} {a.running_total.toFixed(2)}</small></div>):<div style={{padding:"10px 12px",background:"#f8fafc",border:"1px solid #e4e7ec",borderRadius:8,fontWeight:700}}>Sin regla aplicada</div>}</div>:null}</section></div>:null}
  </>
}
function Result({label,value}:{label:string;value:string}){return <div style={{background:"#f8fafc",border:"1px solid #e4e7ec",borderRadius:9,padding:10}}><small style={{color:"#667085"}}>{label}</small><strong style={{display:"block",fontSize:18}}>{value}</strong></div>}
const card:React.CSSProperties={background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:15};
const cell:React.CSSProperties={padding:"8px 7px",borderBottom:"1px solid #eef0f3"};
const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:2000,background:"rgba(16,34,63,.58)",display:"grid",placeItems:"center",padding:20};
const modal:React.CSSProperties={width:"min(920px,96vw)",maxHeight:"90vh",overflowY:"auto",background:"white",borderRadius:16,boxShadow:"0 24px 80px rgba(0,0,0,.28)",padding:20};
