"use client";

import Link from "next/link";
import { RefreshCw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Reservation={id:string;reference:string;product_name:string;provider:string;origin_iata?:string|null;destination_iata?:string|null;departure_date?:string|null;return_date?:string|null;adults:number;children:number;currency?:string|null;price_display?:string|null;contact_name:string;contact_email:string;contact_phone?:string|null;referral_code?:string|null;status:string;payment_status:string;created_at:string};
type Payload={reservations?:Reservation[];metrics?:{reservations?:number;reservations_open?:number};message?:string};

const card:React.CSSProperties={background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:14};
const th:React.CSSProperties={textAlign:"left",padding:"7px 9px",border:"1px solid #dfe4ea",background:"#eef2f5",fontSize:10,textTransform:"uppercase",color:"#536273"};
const td:React.CSSProperties={padding:"8px 9px",border:"1px solid #e3e7eb",fontSize:12,verticalAlign:"top"};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,background:"white"};

function shortDate(value?:string|null){return value?new Date(`${value}T12:00:00`).toLocaleDateString("es-PE"):"—"}

export default function ReservationsPanel(){
  const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/admin/overview",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.message||"No pudimos cargar las reservas.");setData(payload)}catch(e){setError(e instanceof Error?e.message:"No pudimos cargar las reservas.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const reservations=useMemo(()=>{const rows=data?.reservations||[],q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(row=>[row.reference,row.product_name,row.contact_name,row.contact_email,row.origin_iata,row.destination_iata,row.referral_code,row.status,row.payment_status].some(value=>String(value||"").toLowerCase().includes(q)))},[data,search]);
  async function changeStatus(id:string,status:string){setBusy(id);setError("");try{const response=await fetch(`/api/admin/reservations/${encodeURIComponent(id)}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const payload=await response.json();if(!response.ok)throw new Error(payload.message||"No pudimos actualizar la reserva.");await load()}catch(e){setError(e instanceof Error?e.message:"No pudimos actualizar la reserva.")}finally{setBusy("")}}
  return <div style={{maxWidth:1500,margin:"0 auto",color:"#17233b"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"end",marginBottom:14,flexWrap:"wrap"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:900,letterSpacing:1.1,textTransform:"uppercase"}}>Rumbo · PostgreSQL</p><h1 style={{fontSize:32,margin:"4px 0"}}>Reservas</h1><p style={{margin:0,color:"#667085"}}>Operaciones creadas por el storefront y persistidas en el motor nativo de Rumbo.</p></div><button type="button" onClick={()=>void load()} disabled={loading} style={{display:"inline-flex",alignItems:"center",gap:7,padding:"9px 12px",border:"1px solid #cfd5df",borderRadius:8,background:"white",fontWeight:800,cursor:"pointer"}}><RefreshCw size={15}/>{loading?"Actualizando…":"Actualizar"}</button></div>
    {error?<div style={{padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8,marginBottom:10}}>{error}</div>:null}
    <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(180px,260px))",gap:10,marginBottom:12}}><div style={card}><small style={{color:"#667085",fontWeight:800}}>Reservas</small><strong style={{display:"block",fontSize:26,marginTop:4}}>{data?.metrics?.reservations??data?.reservations?.length??0}</strong></div><div style={card}><small style={{color:"#667085",fontWeight:800}}>Abiertas</small><strong style={{display:"block",fontSize:26,marginTop:4}}>{data?.metrics?.reservations_open??0}</strong></div></div>
    <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap",marginBottom:10}}><div><h2 style={{margin:"0 0 3px"}}>Lista de reservas</h2><small style={{color:"#667085"}}>{reservations.length} resultado{reservations.length===1?"":"s"}</small></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar reserva, cliente, destino o referido…" style={{...field,width:"min(460px,100%)"}}/></div>
      {loading&&!data?<div style={{padding:30,textAlign:"center",color:"#667085"}}>Cargando reservas desde PostgreSQL…</div>:null}
      {!loading&&data&&reservations.length===0?<div style={{padding:"34px 16px",textAlign:"center",border:"1px dashed #cfd5df",borderRadius:10,background:"#fafbfc"}}><strong style={{display:"block",fontSize:17}}>No hay reservas guardadas en PostgreSQL</strong><p style={{margin:"7px auto 0",maxWidth:680,color:"#667085",lineHeight:1.5}}>Las nuevas reservas de productos propios de Rumbo aparecerán aquí inmediatamente después de ser creadas. Si acabas de reservar, usa Actualizar.</p></div>:null}
      {reservations.length?<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1120}}><thead><tr>{["Reserva","Cliente","Viaje","Fechas","Pasajeros","Precio","Pago","Estado",""].map((h,i)=><th key={`${h}-${i}`} style={th}>{h}</th>)}</tr></thead><tbody>{reservations.map(row=><tr key={row.id}><td style={td}><strong>{row.reference}</strong><small style={{display:"block",color:"#7d8796",marginTop:3}}>{row.product_name}</small><small style={{display:"block",color:"#98a2b3"}}>{row.provider}</small></td><td style={td}><strong>{row.contact_name}</strong><small style={{display:"block",color:"#7d8796",marginTop:3}}>{row.contact_email}</small></td><td style={td}>{row.origin_iata||"—"} → {row.destination_iata||"—"}<small style={{display:"block",color:"#7d8796",marginTop:3}}>{row.referral_code?`Referido ${row.referral_code}`:"Venta directa"}</small></td><td style={td}>{shortDate(row.departure_date)}<small style={{display:"block",color:"#7d8796",marginTop:3}}>Ret. {shortDate(row.return_date)}</small></td><td style={td}>{row.adults} ad. · {row.children} niñ.</td><td style={td}>{row.price_display||"—"}</td><td style={td}><span style={{padding:"4px 7px",borderRadius:999,background:"#eef3f7",fontWeight:800,fontSize:10}}>{row.payment_status}</span></td><td style={td}><select disabled={busy===row.id} value={row.status} onChange={e=>void changeStatus(row.id,e.target.value)} style={{...field,padding:"5px 7px",fontSize:11}}><option value="new">Nueva</option><option value="validating">Validando</option><option value="quoted">Cotizada</option><option value="confirmed">Confirmada</option><option value="cancelled">Cancelada</option><option value="expired">Vencida</option></select></td><td style={td}><Link href={`/admin/reservas/${row.id}`} style={{color:"#175cd3",fontWeight:800,textDecoration:"none"}}>Ver ›</Link></td></tr>)}</tbody></table></div>:null}
    </section>
  </div>
}
