"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type User={account_id:string;first_name:string;last_name:string;internal_role:"admin"|"counter";email:string;status:string;job_title?:string|null;phone?:string|null;document_type?:string|null;document_number?:string|null;date_of_birth?:string|null;last_login_at?:string|null};
type Credentials={username:string;temporary_password:string;must_change_password:boolean};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};
const th:React.CSSProperties={textAlign:"left",padding:"7px 9px",border:"1px solid #dfe4ea",background:"#eef2f5",color:"#536273",fontSize:10,fontWeight:800,textTransform:"uppercase"};
const td:React.CSSProperties={padding:"7px 9px",border:"1px solid #e3e7eb",fontSize:12,verticalAlign:"middle"};
const primary:React.CSSProperties={background:"#10223f",color:"white",padding:"8px 11px",borderRadius:8,fontWeight:800,fontSize:12,border:0,cursor:"pointer"};

export default function UsersPanel(){
  const [users,setUsers]=useState<User[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null),[showForm,setShowForm]=useState(false),[page,setPage]=useState(1),[search,setSearch]=useState("");
  async function load(){const r=await fetch("/api/admin/user-management",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.message||"No pudimos cargar usuarios.");setUsers(p.users||[])}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/user-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"internal_user",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear el usuario.");else{setCredentials(p.credentials);setShowForm(false);await load()}setBusy(false)}
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?users.filter(u=>[u.first_name,u.last_name,u.email,u.document_number,u.job_title,u.internal_role].some(v=>String(v||"").toLowerCase().includes(q))):users},[users,search]);
  const perPage=10,pages=Math.max(1,Math.ceil(filtered.length/perPage)),rows=filtered.slice((page-1)*perPage,page*perPage);
  return <>
    <section style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:16}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 3px",fontSize:20}}>Usuarios Rumbo</h2><p style={{margin:0,color:"#667085",fontSize:12}}>Personas internas · Administradores y Counters.</p></div><button style={primary} onClick={()=>setShowForm(true)}>+ Nuevo usuario</button></div>
      <div style={{display:"flex",gap:8,margin:"12px 0 8px"}}><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar nombre, DNI, correo o cargo…" style={{flex:1,padding:"9px 11px",border:"1px solid #cfd6df",borderRadius:7}}/></div>
      {error?<div style={{padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8,marginBottom:8}}>{error}</div>:null}
      <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12,minWidth:950}}><thead><tr>{["Nombre","Documento","Fecha nac.","Correo","Rol","Cargo","Último ingreso","Estado"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(u=><tr key={u.account_id}><td style={td}><b>{u.first_name} {u.last_name}</b></td><td style={td}>{u.document_number?<button className="rumbo-person-doc-link" data-person-type="internal" data-person-id={u.account_id}>{u.document_type||"DNI"} {u.document_number}</button>:"—"}</td><td style={td}>{u.date_of_birth?new Date(`${u.date_of_birth}T12:00:00`).toLocaleDateString("es-PE"):"—"}</td><td style={td}>{u.email}</td><td style={td}>{u.internal_role==="admin"?"Administrador":"Counter"}</td><td style={td}>{u.job_title||"—"}</td><td style={td}>{u.last_login_at?new Date(u.last_login_at).toLocaleString("es-PE"):"Nunca"}</td><td style={td}>{u.status}</td></tr>)}</tbody></table></div>
      <div style={{display:"flex",justifyContent:"flex-end",gap:8,alignItems:"center",marginTop:9,fontSize:12,color:"#667085"}}><span>{filtered.length} usuarios · Página {page} de {pages}</span><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>‹ Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Siguiente ›</button></div>
    </section>
    {showForm?<div onClick={()=>setShowForm(false)} style={overlay}><form onSubmit={submit} onClick={e=>e.stopPropagation()} style={modal}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Usuarios Rumbo</p><h2 style={{margin:"4px 0"}}>Nuevo usuario</h2></div><button type="button" onClick={()=>setShowForm(false)} style={{border:0,background:"transparent",fontSize:26}}>×</button></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14}}><label style={label}>Nombres<input name="first_name" required style={field}/></label><label style={label}>Apellidos<input name="last_name" required style={field}/></label><label style={label}>Tipo documento<select name="document_type" defaultValue="DNI" style={field}><option>DNI</option><option>CE</option><option>PASSPORT</option></select></label><label style={label}>Nro. documento<input name="document_number" required style={field}/></label><label style={label}>Fecha de nacimiento<input name="date_of_birth" type="date" style={field}/></label><label style={label}>Teléfono<input name="phone" style={field}/></label><label style={label}>Correo<input name="email" type="email" required style={field}/></label><label style={label}>Rol<select name="role" defaultValue="counter" style={field}><option value="counter">Counter Rumbo</option><option value="admin">Administrador Rumbo</option></select></label><label style={{...label,gridColumn:"1/-1"}}>Cargo<input name="job_title" placeholder="Gerente / Ejecutivo / Counter" style={field}/></label></div><button disabled={busy} style={{...primary,marginTop:14}}>{busy?"Creando…":"Crear usuario"}</button></form></div>:null}
    {credentials?<div onClick={()=>setCredentials(null)} style={{...overlay,zIndex:2200}}><div onClick={e=>e.stopPropagation()} style={{...modal,width:"min(480px,100%)"}}><h2 style={{marginTop:0}}>Usuario creado</h2><p style={{color:"#667085"}}>Entrega estas credenciales una sola vez.</p><div style={{background:"#f8fafc",padding:14,borderRadius:10}}><small>Usuario</small><b style={{display:"block",fontSize:17}}>{credentials.username}</b><small style={{display:"block",marginTop:10}}>Contraseña temporal</small><b style={{display:"block",fontSize:20}}>{credentials.temporary_password}</b></div><button onClick={()=>setCredentials(null)} style={{...primary,marginTop:14}}>Entendido</button></div></div>:null}
  </>
}
const overlay:React.CSSProperties={position:"fixed",inset:0,background:"rgba(16,24,40,.58)",display:"grid",placeItems:"center",zIndex:2000,padding:20};
const modal:React.CSSProperties={width:"min(720px,100%)",background:"white",borderRadius:14,padding:20,boxShadow:"0 24px 80px rgba(0,0,0,.28)"};
