"use client";

import { Building2, Eye, EyeOff, LoaderCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { FormEvent, useState } from "react";
import styles from "../acceso.module.css";

export default function RetailerLoginPage(){
 const [showPassword,setShowPassword]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setLoading(true);const form=new FormData(event.currentTarget);try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({access_type:"retailer",email:String(form.get("email")||"").trim(),password:String(form.get("password")||""),remember:form.get("remember")==="on"})});const result=await response.json();if(!response.ok)throw new Error(result.message||"No pudimos iniciar sesión.");if(!["retailer_owner","retailer_agent"].includes(result?.account?.role)){await fetch("/api/auth/logout",{method:"POST"}).catch(()=>{});throw new Error("Esta cuenta no pertenece a una agencia minorista.");}if(!result?.profile?.retailer_id)throw new Error("El usuario no está vinculado a una agencia minorista.");window.location.assign("/agencia");}catch(e){setError(e instanceof Error?e.message:"No pudimos iniciar sesión.");}finally{setLoading(false);}}
 return <main className={styles.page}><section className={styles.brandPanel}><Link className={styles.brand} href="/">rumbo<span>.</span></Link><div className={styles.brandContent}><p className={styles.eyebrow}>Portal minorista</p><h1>Tu agencia conectada a Rumbo.</h1><p>Accede con el usuario creado dentro de tu agencia para gestionar ventas, reservas y operación comercial.</p><div className={styles.benefits}><div><Building2/><span>Cada usuario entra únicamente a la agencia a la que está vinculado</span></div><div><ShieldCheck/><span>Roles Administrador y Counter respetados desde PostgreSQL</span></div></div></div></section><section className={styles.formPanel}><div className={styles.card}><div className={styles.heading}><p className={styles.eyebrow}>AGENCIAS MINORISTAS</p><h2>Iniciar sesión</h2><p>Usa el correo registrado como usuario de tu agencia.</p></div><form className={styles.form} onSubmit={submit}><label>Correo electrónico<input name="email" type="email" required autoComplete="email"/></label><label>Contraseña<div className={styles.passwordField}><input name="password" type={showPassword?"text":"password"} required autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label="Mostrar u ocultar contraseña">{showPassword?<EyeOff/>:<Eye/>}</button></div></label><div className={styles.loginOptions}><label className={styles.check}><input name="remember" type="checkbox"/><span>Recordarme</span></label><Link href="/olvide-contrasena">Olvidé mi contraseña</Link></div>{error?<div className={styles.success} role="alert"><ShieldCheck/><div><strong>No pudimos ingresar</strong><p>{error}</p></div></div>:null}<button className={styles.submit} disabled={loading}>{loading?<><LoaderCircle className="button-loader"/> Ingresando…</>:"Ingresar a mi agencia"}</button></form></div><p className={styles.back}>¿Eres Partner? <Link href="/acceso/partner">Acceso Partners →</Link></p></section></main>;
}
