"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Retailer={id:string;trade_name:string;legal_name:string;tax_id:string};
type Credentials={username:string;temporary_password:string;must_change_password:boolean};
const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};

export default function NewAgencyPersonPage(){
  const [agencies,setAgencies]=useState<Retailer[]>([]),[retailer,setRetailer]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[credentials,setCredentials]=useState<Credentials|null>(null);
  useEffect(()=>{fetch("/api/admin/overview",{cache:"no-store"}).then(r=>r.json().then(p=>({r,p}))).then(({r,p})=>{if(!r.ok)throw new Error(p.message||"No pudimos cargar agencias.");setAgencies(p.retailers||[]);const q=new URLSearchParams(location.search).get("retailer");if(q)setRetailer(q);else if(p.retailers?.[0])setRetailer(p.retailers[0].id)}).catch(e=>setError(e.message))},[]);
  const selected=useMemo(()=>agencies.find(a=>a.id===retailer),[agencies,retailer]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/user-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"agency_person",retailer_id:retailer,...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear la persona.");else{setCredentials(p.credentials);e.currentTarget.reset()}setBusy(false)}
  return <main style={{minHeight:"100vh",background:"#f6f7f9",padding:"18px 24px",color:"#17233b"}}><div style={{maxWidth:760,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Rumbo · Personas de agencia</p><h1 style={{margin:"4px 0"}}>Nueva persona</h1></div><Link href="/admin/agencias" style={{textDecoration:"none",color:"#344054"}}>← Agencias</Link></div>{selected?<p style={{margin:"8px 0 0",color:"#667085"}}>Agencia: <b>{selected.trade_name}</b> · {selected.tax_id}</p>:null}{error?<div style={{marginTop:12,padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8}}>{error}</div>:null}
    <form onSubmit={submit} style={{marginTop:14,background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:16}}><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><label style={label}>Agencia<select value={retailer} onChange={e=>setRetailer(e.target.value)} required style={field}>{agencies.map(a=><option key={a.id} value={a.id}>{a.trade_name} · {a.tax_id}</option>)}</select></label><label style={label}>Rol<select name="role" defaultValue="counter" style={field}><option value="counter">Counter</option><option value="admin">Administrador</option></select></label><label style={label}>Nombres<input name="first_name" required style={field}/></label><label style={label}>Apellidos<input name="last_name" required style={field}/></label><label style={{...label,gridColumn:"1 / -1"}}>Correo de acceso<input name="email" type="email" required style={field}/></label></div><button disabled={busy||!retailer} style={{marginTop:12,border:0,borderRadius:8,padding:"10px 14px",background:"#10223f",color:"white",fontWeight:800}}>{busy?"Creando…":"Crear persona"}</button></form>
    {credentials?<div onClick={()=>setCredentials(null)} style={{position:"fixed",inset:0,background:"rgba(16,24,40,.55)",display:"grid",placeItems:"center",zIndex:1000,padding:20}}><div onClick={e=>e.stopPropagation()} style={{width:"min(480px,100%)",background:"white",borderRadius:14,padding:20,boxShadow:"0 24px 80px rgba(0,0,0,.28)"}}><h2 style={{marginTop:0}}>Persona creada</h2><p style={{color:"#667085"}}>Estas credenciales se muestran para entregarlas al usuario. La contraseña es temporal.</p><div style={{background:"#f8fafc",padding:14,borderRadius:10}}><small>Usuario</small><b style={{display:"block",fontSize:17}}>{credentials.username}</b><small style={{display:"block",marginTop:10}}>Contraseña temporal</small><b style={{display:"block",fontSize:20}}>{credentials.temporary_password}</b></div><button onClick={()=>setCredentials(null)} style={{marginTop:14,border:0,borderRadius:8,padding:"9px 13px",background:"#10223f",color:"white",fontWeight:800}}>Entendido</button></div></div>:null}
  </div></main>
}
