"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const field:React.CSSProperties={padding:"9px 10px",border:"1px solid #cfd5df",borderRadius:7,width:"100%",background:"white"};
const label:React.CSSProperties={display:"grid",gap:5,fontSize:12,color:"#475467"};

export default function NewAgencyPage(){
  const [error,setError]=useState(""),[busy,setBusy]=useState(false),[created,setCreated]=useState<any>(null);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/user-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"agency",...Object.fromEntries(f.entries())})});const p=await r.json();if(!r.ok)setError(p.message||"No pudimos crear la agencia.");else setCreated(p.agency);setBusy(false)}
  return <main style={{minHeight:"100vh",background:"#f6f7f9",padding:"18px 24px",color:"#17233b"}}><div style={{maxWidth:980,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{margin:0,color:"#e9573b",fontSize:10,fontWeight:800,textTransform:"uppercase"}}>Rumbo · Agencias</p><h1 style={{margin:"4px 0"}}>Nueva agencia</h1></div><Link href="/admin/agencias" style={{textDecoration:"none",color:"#344054"}}>← Volver</Link></div>{error?<div style={{marginTop:12,padding:10,border:"1px solid #fecaca",background:"#fff5f5",color:"#991b1b",borderRadius:8}}>{error}</div>:null}
    <form onSubmit={submit} style={{marginTop:14,background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:16}}><h2 style={{margin:"0 0 10px",fontSize:17}}>Datos legales y comerciales</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><label style={label}>Nombre comercial<input name="trade_name" required style={field}/></label><label style={label}>Razón social<input name="legal_name" required style={field}/></label><label style={label}>RUC<input name="tax_id" required style={field}/></label><label style={label}>Contacto principal<input name="contact_name" style={field}/></label><label style={label}>Correo<input name="contact_email" type="email" style={field}/></label><label style={label}>Teléfono<input name="contact_phone" style={field}/></label><label style={label}>Dirección<input name="address" style={field}/></label><label style={label}>Ciudad<input name="city" defaultValue="Lima" style={field}/></label><label style={label}>País<input name="country" defaultValue="Perú" style={field}/></label><label style={label}>Límite de usuarios<input name="user_limit" type="number" min="1" defaultValue="10" style={field}/></label><label style={label}>Días de inactividad<input name="inactivity_days" type="number" min="1" defaultValue="30" style={field}/></label></div>
    <h2 style={{margin:"18px 0 10px",fontSize:17}}>Datos bancarios</h2><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><label style={label}>Banco principal<input name="bank_name" placeholder="BCP / BBVA / Interbank" style={field}/></label><label style={label}>Titular de la cuenta<input name="bank_account_holder" style={field}/></label><label style={label}>Número de cuenta<input name="bank_account_number" style={field}/></label><label style={label}>CCI<input name="bank_cci" style={field}/></label><label style={label}>Moneda<select name="bank_account_currency" defaultValue="PEN" style={field}><option>PEN</option><option>USD</option><option>EUR</option></select></label></div><label style={{...label,marginTop:10}}>Observaciones<textarea name="notes" style={{...field,minHeight:70}}/></label><button disabled={busy} style={{marginTop:12,border:0,borderRadius:8,padding:"10px 14px",background:"#10223f",color:"white",fontWeight:800}}>{busy?"Creando…":"Crear agencia"}</button></form>
    {created?<div style={{marginTop:12,padding:14,borderRadius:10,background:"#ecfdf3",border:"1px solid #abefc6"}}><b>Agencia creada:</b> {created.trade_name} · {created.tax_id}. <Link href={`/admin/agencias/personas/nueva?retailer=${created.id}`}>Crear su primer usuario</Link></div>:null}
  </div></main>
}
