-- Credenciales temporales individuales para usuarios TEST de Partners y agencias minoristas.
-- Las contraseñas en texto plano NO se guardan en el repositorio; solo hashes bcrypt.
-- Todos los usuarios quedan obligados a cambiar contraseña en el primer ingreso.

UPDATE rumbo_accounts SET password_hash='$2b$12$VxwhdKdVANh8Em9ze7k1N.MKjApYKS4FhPM6gNVze1ggFXTujMnuq', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin@newtravel.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$TtltUbdhmb3e3xU5K5fX0ekOcpLTomv1EIUt4vcwxL5Ym0yjzCTD6', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1@newtravel.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$udaNRmRf6A6eR09RNVCC4O25dssTKzV0jZwpg7ZPeNI2jePhMaJVi', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$HVEgN.OniZ8EiZGLwF4vPOVVCFyRSZxZmxevnvflencemQvW4LQB2', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$PzJKnlyTk9YNWoryqQt9../eBbKv2p658S5lXQ/W4tIfYIOOSHsiu', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$tjsfkAW/BPirOSspG/ZAE.P6AG8SyKutaNRqGvsgByFVpsJynFaC6', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$VGAPqOp/NdEXTcj0bnaLW.93BA5iiBIhgti90Hbn8YCzgGrIhDvZi', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$XBP/JLqEKymlN5GQyGoXXOKmJQU6D0HXexVDdQXfYipc6EWTBZWsi', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag03@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$6W0N9ucJgWa.cT0rMcShTeuMF28H0Oh2tirx5ieArdct0HT5T71dO', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$Msb5CC0hy/rGMZl31dRG/uk/tcRuTnpS80kRFmYqsesAbssr45l.y', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$7SuhRgBq5rsf4fiie9rX7uH0HUizHFJ.A1Gelr1OckbwJV2X9zX06', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$Oi/RVgu0BTKzwBKdtObgo.bNXLgOgymVlOuBMK4hW8kHV3XyuvPIm', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$KgyE95iykx/4gQ31edzJqewAoe.vpzXNorw0gWIeMIpEGR2qe28YK', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$bI1NGRNjXv0FDYC6z7iciOatRVEWNQO30p6Xf/3DK99RHSKverSO6', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag06@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$eGzHBgI5ABV9sBjcriHZW.oEmKNJi4vb5igjGidi0MZ61Iq9dzhNG', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$sOOTKNBIh.Zq9k2/RrMAeeopw/rPhonRMHm8UvhFPjv1/B12u/YbG', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$vRC9vhf36HTSbs3gAU.4iOaN2w2la2jTTh9lcBq/ypSAuFBbdPtb.', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$p.TUBiDXnnpfd9CjWxxjleByIf8TJZddd2SZ4Fl2Kk8xAdyr2SfxW', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$CJCcIIKHgVmVL3Z14k0EqOq/3jIReEdc4K0D89CYPnf1wCALpoQz6', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$.9xkYrejx40QucuXYf5RMea76Z7Kht7JSfvqZlsAncaquxNDZ0YqC', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag09@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$EsXW8yyWKbWNG.TSB89pXuvCmd.d5yj1/KEMTOz7jR2NpZ3.8UKXO', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$11cz722Pkx.qpBbrKLotuurk3.XYqtXkPEyKyon5oU4LRXKIfmtEa', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$sG7R0ZevdMo.TnCKKhwo9e2EY/uX/fzeBeycczQAk2b9uXlTze8r2', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner03@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$GK9XE2ZeXz4hvwr9h.FR3OfoUB1WV9z/1f3HJo5D6dzZh9dURqrnC', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$z59F9sD9HQftvw1uNMn52.vq7Fi1rll5j69VpaXjNT5cYgJMRVkTq', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$3faSNjx38ZZfYu3MRLRat.6yaLgL.oabsCF/ZgXZtLZZfgGExuPxu', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner06@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$uvjShqEcmCcUNyPrdvB9meu3fdv6AnFCdyHlj0YX2auplDBhek0QO', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$.tR9SAmg6Vr459vIzOPWUuBIWjg3Ym6Qyfk61YABawr0LA2QGezR6', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$V3FRgVaSQFgp4YQH/Fm6su9GQBfStUzRONwonaVBgUHYZZaKBRj/e', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner09@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$EO2UWBg9Ebu3hbY/isFWtu/Inbp8HYqQTptq4SV4U7DcKHo29EAg.', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner10@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$EIGSmRwFygjzW3p4EIhyTuuBTj62ajhbQyyaWInPD.8mKlnffQBsi', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner11@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$Z.NA2.CWrnJxHJvlZhyM3.372R9mTIWEx8UGmPmMmVckDzFRIFdiu', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner12@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$LKFUUDjP0pxi8GcAe/z/yOVonWmZGHrL24XUOCQCAakxy0kbYodmy', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner13@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$qEKy0lHZEuMxcrloVSx66uzMGksCAKs1lwwuPnVvxanYeYvjNiS1G', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner14@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$/x3jPetCJC8/0gPZqJRiwOzW8Le3zQxzO2VaAnUX0GIb5OiOnwuI2', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner15@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$PrMMKIJwk0rZ1dif/.UC6eLPhDm/swr0zEJZFWWfNLfjFyREhxrym', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner16@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$gQBolcn4tJyhUfh2V3oxsuPQ2ftNf4mEtGnEwDJkgaQoMrtm9y.4m', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner17@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$v7TU1qttYv0VL4PTMp0vYeF8VqN5hkKXRcVVW8gAJ/Ac6O73Eyws2', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner18@rumbo-test.pe');
