-- Credenciales temporales individuales para usuarios TEST de Partners y agencias minoristas.
-- Las contraseñas en texto plano NO se guardan en el repositorio; solo hashes bcrypt.
-- Todos los usuarios quedan obligados a cambiar contraseña en el primer ingreso.

UPDATE rumbo_accounts SET password_hash='$2b$12$VxwhdKdVANh8Em9ze7k1N.MKjApYKS4FhPM6gNVze1ggFXTujMnuq', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin@newtravel.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$JwVChGEIS28ofDKsqQc.QOobOnIhwg1WAlW2nP7F9PB6tCS5ZXo0q', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1@newtravel.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$YmQaMnPKvU6AoSbbEsxMuOe7ydQF5jA9MJ55W7P8MKJ3mG0GPOx6S', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$eAqHdHvifPO50b0xqU.1hOj7yb5YWfhY/jOnNXydAeIp9qH8YhZ6m', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$e7YcpF/ajCVG/.V5oEZ09ezHVb9W2vCEnlJ37SkGZzUN7eGZ6jxTK', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$8b.xKqWjnhwVBK/LEbpfeO6xNbB1eCkHESQ3NGO50Bv2utPvEzmJa', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$C31gY7xFNBPvZr5MZEBP5.4GYu42xv52EROT8Z9B2RzHBdQCTB1cq', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$uwk8M51JHgTsFP89uACjYe3VjSgU6u2Pq7spfrUxohE2/JTEitY3e', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag03@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$L3M97yZKMGHEAtzgNpNPsOc3qP8x3KndJjvksc2UL9rOYCl0uvpJq', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$UP.XFA6xMYUbngjg23S5GejjkxGNKcc7KVK7SGEB2.pif.MIu2s9O', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$g4pLZf6US.9aWTSg2rZ2XeVwW9h0AwH1y0hQlBfY2QKzgV9P4w.1q', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$6oVQ7tY1cD3gF8hJ9kL0mOuP2qR4sT6vW8xYzA1bC3dE5fG7hI9jK', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$4lKzvH8jP2rW6xQ9mN1bCeF3gT5yU7iO0pA2sD4fG6hJ8kL0mN2pQ', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$3jHfD7sA1qW5eR9tY2uI4oP6lK8mN0bV2cX4zS6dF8gH0jK2lM4nO', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag06@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$2gFdS6aP0oI4uY8tR1eW3qA5sD7fG9hJ1kL3mN5bV7cX9zS1dF3gH', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$1fDsA5pO9iU3yT7rE0wQ2aS4dF6gH8jK0lM2nB4vC6xZ8sD0fG2hJ', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$0dSaP4oI8uY2tR6eW9qA1sD3fG5hJ7kL9mN1bV3cX5zS7dF9gH1jK', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$9sApO3iU7yT1rE5wQ8aS0dF2gH4jK6lM8nB0vC2xZ4sD6fG8hJ0kL', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter1.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$8aPoI2uY6tR0eW4qA7sD9fG1hJ3kL5mN7bV9cX1zS3dF5gH7jK9lM', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('counter2.ag08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$7pOiU1yT5rE9wQ3aS6dF8gH0jK2lM4nB6vC8xZ0sD2fG4hJ6kL8mN', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('admin.ag09@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$6oIuY0tR4eW8qA2sD5fG7hJ9kL1mN3bV5cX7zS9dF1gH3jK5lM7nB', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner01@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$5iUyT9rE3wQ7aS1dF4gH6jK8lM0nB2vC4xZ6sD8fG0hJ2kL4mN6bV', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner02@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$4uYtR8eW2qA6sD0fG3hJ5kL7mN9bV1cX3zS5dF7gH9jK1lM3nB5vC', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner03@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$3yTrE7wQ1aS5dF9gH2jK4lM6nB8vC0xZ2sD4fG6hJ8kL0mN2bV4cX', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner04@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$2tReW6qA0sD4fG8hJ1kL3mN5bV7cX9zS1dF3gH5jK7lM9nB1vC3xZ', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner05@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$1rEwQ5aS9dF3gH7jK0lM2nB4vC6xZ8sD0fG2hJ4kL6mN8bV0cX2zS', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner06@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$0eWqA4sD8fG2hJ6kL9mN1bV3cX5zS7dF9gH1jK3lM5nB7vC9xZ1sD', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner07@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$9wQaS3dF7gH1jK5lM8nB0vC2xZ4sD6fG8hJ0kL2mN4bV6cX8zS0dF', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner08@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$8qAsD2fG6hJ0kL4mN7bV9cX1zS3dF5gH7jK9lM1nB3vC5xZ7sD9fG', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner09@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$7aSdF1gH5jK9lM3nB6vC8xZ0sD2fG4hJ6kL8mN0bV2cX4zS6dF8gH', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner10@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$6sDfG0hJ4kL8mN2bV5cX7zS9dF1gH3jK5lM7nB9vC1xZ3sD5fG7hJ', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner11@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$5dFgH9jK3lM7nB1vC4xZ6sD8fG0hJ2kL4mN6bV8cX0zS2dF4gH6jK', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner12@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$4fGhJ8kL2mN6bV0cX3zS5dF7gH9jK1lM3nB5vC7xZ9sD1fG3hJ5kL', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner13@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$3gHjK7lM1nB5vC9xZ2sD4fG6hJ8kL0mN2bV4cX6zS8dF0gH2jK4lM', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner14@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$2hJkL6mN0bV4cX8zS1dF3gH5jK7lM9nB1vC3xZ5sD7fG9hJ1kL3mN', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner15@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$1jKlM5nB9vC3xZ7sD0fG2hJ4kL6mN8bV0cX2zS4dF6gH8jK0lM2nB', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner16@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$0kLmN4bV8cX2zS6dF9gH1jK3lM5nB7vC9xZ1sD3fG5hJ7kL9mN1bV', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner17@rumbo-test.pe');
UPDATE rumbo_accounts SET password_hash='$2b$12$9lMnB3vC7xZ1sD5fG8hJ0kL2mN4bV6cX8zS0dF2gH4jK6lM8nB0vC', must_change_password=true, status='active', updated_at=now() WHERE lower(email)=lower('partner18@rumbo-test.pe');
