-- Production catalog: 22 real supplier products from workbook 2026-09-21.
DELETE FROM rumbo_catalog_products WHERE COALESCE(metadata->>'test_seed','false')='true';
INSERT INTO rumbo_catalog_products(slug,name,short_description,country,country_code,city,destination_iata,provider,provider_reference,duration_label,tag,status,sort_order,metadata) VALUES
('pkg-tpp-001','TARAPOTO EXPRESS 3D/2N','Paquete a Tarapoto con hotel, tours y traslados','Perú','PE','TARAPOTO','TPP','AMAZON GOLD TRAVEL','PKG-TPP-001','3 días / 2 noches','Cultural - Naturaleza','published',1,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-tpp-002','TARAPOTO ESCENCIAL 4D/3N','Paquete a Tarapoto con hotel, tours y traslados','Perú','PE','TARAPOTO','TPP','AMAZON GOLD TRAVEL','PKG-TPP-002','4 días / 3 noches','Cultural - Naturaleza','published',2,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-tpp-003','TARAPOTO MAGICO 5D/4N','Paquete a Tarapoto con hotel, tours y traslados','Perú','PE','TARAPOTO','TPP','AMAZON GOLD TRAVEL','PKG-TPP-003','5 días / 4 noches','Cultural - Naturaleza','published',3,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-tpp-004','TARAPOTO NATURALEZA AMAZONICA 6D/5N','Paquete a Tarapoto con hotel, tours y traslados','Perú','PE','TARAPOTO','TPP','AMAZON GOLD TRAVEL','PKG-TPP-004','6 días / 5 noches','Cultural - Naturaleza','published',4,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-tpp-005','TARAPOTO MAGIA AMAZONICA 7D/6N','Paquete a Tarapoto con hotel, tours y traslados','Perú','PE','TARAPOTO','TPP','AMAZON GOLD TRAVEL','PKG-TPP-005','7 días / 6 noches','Cultural - Naturaleza','published',5,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-jau-006','SELVA CENTRAL VIVA 3D/2N','Paquete a La Merced con hotel, tours y traslados','Perú','PE','JAUJA - LA MERCED','JAU','ANGEL AVENTURA CHANCHAMAYO TOURS','PKG-JAU-006','3 días / 2 noches','Cultural - Naturaleza','published',6,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-jau-007','SELVA CENTRAL DE ENCANTO 4D/3N','Paquete a La Merced con hotel, tours y traslados','Perú','PE','JAUJA - LA MERCED','JAU','ANGEL AVENTURA CHANCHAMAYO TOURS','PKG-JAU-007','4 días / 3 noches','Cultural - Naturaleza','published',7,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-jau-008','SELVA CENTRAL EXPERIENCIA COMPLETA 5D/4N','Paquete a La Merced con hotel, tours y traslados','Perú','PE','JAUJA - LA MERCED','JAU','ANGEL AVENTURA CHANCHAMAYO TOURS','PKG-JAU-008','5 días / 4 noches','Cultural - Naturaleza','published',8,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-tum-009','VERANO ETERNO 4D/3N','Paquete a Playas del norte con hotel y traslados','Perú','PE','TUMBES','TBP','HOTEL DIRECTO Y TRASLADOS','PKG-TUM-009','4 dias / 3 noches','Playa','published',9,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-ata-010','ESCAPADA A HUARAZ 2D/1N','Paquetes a Huaraz con hotel, traslados y tours','Perú','PE','HUARAZ','ATA','LALO TRAVEL','PKG-ATA-010','2 días / 1 noches','Aventura - Naturaleza','published',10,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-ata-011','HUARAZ NATURAL 3D/2N','Paquetes a Huaraz con hotel, traslados y tours','Perú','PE','HUARAZ','ATA','LALO TRAVEL','PKG-ATA-011','3 días / 2 noches','Aventura - Naturaleza','published',11,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-ata-012','HUARAZ FASCINANTE 4D/3N','Paquetes a Huaraz con hotel, traslados y tours','Perú','PE','HUARAZ','ATA','LALO TRAVEL','PKG-ATA-012','4 días / 3 noches','Aventura - Naturaleza','published',12,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-ata-013','DESCUBRE HUARAZ 5D/4N','Paquetes a Huaraz con hotel, traslados y tours','Perú','PE','HUARAZ','ATA','LALO TRAVEL','PKG-ATA-013','5 días / 4 noches','Aventura - Naturaleza','archived',13,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cuz-014','EL CAMINO DEL SOL 4D/3N','Paquete a Cusco con hotel, entradas, traslados, tren y tours','Perú','PE','CUZCO','CUZ','MACHUPICCHU BY WORLD','PKG-CUZ-014','4 días / 3 noches','Cultural - Naturaleza','archived',14,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cuz-015','ESENCIA DE LOS ANDES 5D/4N','Paquete a Cusco con hotel, entradas, traslados, tren y tours','Perú','PE','CUZCO','CUZ','MACHUPICCHU BY WORLD','PKG-CUZ-015','5 días / 4 noches','Cultural - Naturaleza','archived',15,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cuz-016','SECRETO DE LOS ANDES 6D/5N','Paquete a Cusco con hotel, entradas, traslados, tren y tours','Perú','PE','CUZCO','CUZ','MACHUPICCHU BY WORLD','PKG-CUZ-016','6 días / 5 noches','Cultural - Naturaleza','archived',16,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cja-017','ENCANTOS DE CAJAMARCA 3D/2N','Paquete a Cajamarca hotel, tours, traslados y entradas','Perú','PE','CAJAMARCA','CJA','TM TRAVEL','PKG-CJA-017','3 días / 2 noches','Cultural - Naturaleza','archived',17,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cja-018','MAGIA ANCINA EN CAJAMARCA 4D/3N','Paquete a Cajamarca hotel, tours, traslados y entradas','Perú','PE','CAJAMARCA','CJA','TM TRAVEL','PKG-CJA-018','4 días / 3 noches','Cultural - Naturaleza','archived',18,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-cja-019','RUTA CULTURAL EN CAJAMARCA 5D/4N','Paquete a Cajamarca hotel, tours, traslados y entradas','Perú','PE','CAJAMARCA','CJA','TM TRAVEL','PKG-CJA-019','5 días / 4 noches','Cultural - Naturaleza','archived',19,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-aqp-020','ENCANTOS DE AREQUIPA 4D/3N','Paquete Arequipa hotel, tours, traslados y entradas','Perú','PE','AREQUIPA','AQP','ANDERRA TRAVEL','PKG-AQP-020','4 días / 3 noches','Aventura - Cultural - Naturaleza','archived',20,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-aqp-021','MAGIA ANDINA 5D/4N','Paquete Arequipa hotel, tours, traslados y entradas','Perú','PE','AREQUIPA','AQP','ANDERRA TRAVEL','PKG-AQP-021','5 días / 4 noches','Aventura - Cultural - Naturaleza','archived',21,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}'),
('pkg-aqp-022','AREQUIPA MARAVILLOSA 6D/5N','Paquete Arequipa hotel, tours, traslados y entradas','Perú','PE','AREQUIPA','AQP','ANDERRA TRAVEL','PKG-AQP-022','6 días / 5 noches','Aventura - Cultural - Naturaleza','archived',22,'{"real_catalog":true,"source":"supplier-workbook-2026-09-21"}')
ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,short_description=EXCLUDED.short_description,country=EXCLUDED.country,country_code=EXCLUDED.country_code,city=EXCLUDED.city,destination_iata=EXCLUDED.destination_iata,provider=EXCLUDED.provider,provider_reference=EXCLUDED.provider_reference,duration_label=EXCLUDED.duration_label,tag=EXCLUDED.tag,status=EXCLUDED.status,sort_order=EXCLUDED.sort_order,metadata=EXCLUDED.metadata;
