import { accessConfiguration, backendMessage, parseJson, providerHeaders } from "./rumbo-access.ts";
import type { TravelPackage } from "./travel-packages.ts";

export type PackageSearchInput={originIata:string;destinationIata:string;destinationName:string;departureDate:string;returnDate:string;adults:number;currency:string};
export type PackageSearchResult={mode:"live";provider:"PriceTravel";packages:TravelPackage[];message:string};
type UnknownRecord=Record<string,unknown>;
export class PriceTravelError extends Error{readonly status:number;constructor(message:string,status=502){super(message);this.name="PriceTravelError";this.status=status}}
const record=(value:unknown):UnknownRecord|null=>value!==null&&typeof value==="object"&&!Array.isArray(value)?value as UnknownRecord:null;
function firstString(source:UnknownRecord,names:string[]){for(const name of names){const value=source[name];if(typeof value==="string"&&value.trim())return value.trim()}return undefined}
function firstNumber(source:UnknownRecord,names:string[]){for(const name of names){const value=source[name];if(typeof value==="number"&&Number.isFinite(value))return value;if(typeof value==="string"&&value.trim()&&Number.isFinite(Number(value)))return Number(value)}return undefined}
function packageItems(payload:unknown):unknown[]{if(Array.isArray(payload))return payload;const root=record(payload);if(!root)return[];for(const key of["Packages","packages","Results","results","Data","data"])if(Array.isArray(root[key]))return root[key] as unknown[];return[]}
function includedItems(source:UnknownRecord){const raw=source.Included??source.included??source.Includes??source.includes??source.Services??source.services;if(Array.isArray(raw)){const values=raw.map(item=>typeof item==="string"?item.trim():record(item)?firstString(record(item)!,["Name","name","Description","description"]):undefined).filter((item):item is string=>Boolean(item));if(values.length)return values.slice(0,5)}if(typeof raw==="string"){const values=raw.split(/[|,]/).map(item=>item.trim()).filter(Boolean);if(values.length)return values.slice(0,5)}return[]}
function formatPrice(amount:number|undefined,currency:string){if(amount===undefined)return"Consultar";try{return new Intl.NumberFormat("es-PE",{style:"currency",currency,maximumFractionDigits:0}).format(amount)}catch{return`${currency} ${amount.toFixed(0)}`}}
function mapPackage(value:unknown,index:number,input:PackageSearchInput):TravelPackage|null{const source=record(value);if(!source)return null;const id=firstString(source,["PackageId","packageId","Id","id","Code","code"])||`pricetravel-${index+1}`;const destination=firstString(source,["Name","name","Title","title","PackageName","packageName","DestinationName","destinationName"])||`Paquete a ${input.destinationName}`;const country=firstString(source,["CountryName","countryName","Country","country"])||"Destino internacional";const image=firstString(source,["ImageUrl","imageUrl","Image","image","HotelImageUri","hotelImageUri"])||"/images/rumbo-hero.jpg";const currency=firstString(source,["Currency","currency","CurrencyCode","currencyCode"])||input.currency;const total=firstNumber(source,["TotalAmount","totalAmount","TotalPrice","totalPrice","Price","price"]);const nights=firstNumber(source,["Nights","nights","NumberOfNights","numberOfNights"])||Math.max(1,Math.round((Date.parse(input.returnDate)-Date.parse(input.departureDate))/86_400_000));return{id,destination,country,image,imagePosition:"center",duration:`${nights} noches`,rating:firstString(source,["Rating","rating","Stars","stars"])||"Nuevo",reviews:firstString(source,["Reviews","reviews"])||"0",price:formatPrice(total,currency),previousPrice:"",tag:firstString(source,["Tag","tag","RateType","rateType"])||"PriceTravel",included:includedItems(source),provider:"PriceTravel",providerReference:id,bookable:false}}

export async function searchPriceTravelPackages(input:PackageSearchInput):Promise<PackageSearchResult>{
 const provider=accessConfiguration();if(!provider)throw new PriceTravelError("Rumbo API no está configurada para consultar PriceTravel.",503);
 const query=new URLSearchParams({origin:input.originIata,destination:input.destinationIata,destinationName:input.destinationName,departureDate:input.departureDate,returnDate:input.returnDate,adults:String(input.adults),currency:input.currency});
 let response:Response;try{response=await fetch(`${provider.apiUrl}/api/integrations/pricetravel/packages?${query}`,{headers:providerHeaders(provider),cache:"no-store"})}catch(error){throw new PriceTravelError(error instanceof Error?`No se pudo conectar con PriceTravel: ${error.message}`:"No se pudo conectar con PriceTravel.")}
 const payload=await parseJson(response);if(!response.ok)throw new PriceTravelError(backendMessage(payload,`PriceTravel respondió HTTP ${response.status}.`),response.status);
 const packages=packageItems(payload).map((item,index)=>mapPackage(item,index,input)).filter((item):item is TravelPackage=>item!==null).slice(0,24);
 return{mode:"live",provider:"PriceTravel",packages,message:packages.length?"Paquetes y tarifas consultados directamente en PriceTravel.":"PriceTravel respondió correctamente, pero no encontró paquetes para estas fechas."};
}
