import { accessConfiguration, backendMessage, parseJson, providerHeaders } from "./rumbo-access";

export type CheckoutSummary={amount:string;currency:string;expiresAt:string;paymentId:string;reference:string;returnUrl:string;webhookUrl:string;signature:string};
export type IzipayFormSession={formToken:string;publicKey:string;resultUrl:string;paymentScriptUrl:string;themeScriptUrl:string;themeStylesheetUrl:string};
export type PaymentEvent={event_id:string;event_type:string;booking_reference:string;provider_payment_id:string;status:"pending"|"paid"|"failed"|"cancelled"|"refunded";amount:string;currency:string};
export class PaymentApiError extends Error{readonly status:number;constructor(message:string,status=502){super(message);this.name="PaymentApiError";this.status=status}}
function text(value:unknown){return typeof value==="string"||typeof value==="number"?String(value).trim():""}
async function post(path:string,payload:unknown){const provider=accessConfiguration();if(!provider)throw new PaymentApiError("Rumbo API no está configurada.",503);let response:Response;try{response=await fetch(`${provider.apiUrl}${path}`,{method:"POST",headers:providerHeaders(provider,{json:true}),body:JSON.stringify(payload),cache:"no-store",signal:AbortSignal.timeout(25000)})}catch(error){throw new PaymentApiError(error instanceof Error?`Rumbo API no respondió: ${error.message}`:"Rumbo API no respondió.",502)}const body=await parseJson(response);if(!response.ok)throw new PaymentApiError(backendMessage(body,`Rumbo API respondió HTTP ${response.status}.`),response.status);return body}
export async function openIzipayCheckout(raw:Record<string,string|string[]|undefined>){const one=(key:string)=>{const value=raw[key];return Array.isArray(value)?value[0]||"":typeof value==="string"?value:""};const checkout:CheckoutSummary={amount:one("amount"),currency:one("currency").toUpperCase(),expiresAt:one("expires_at"),paymentId:one("payment_id"),reference:one("reference").toUpperCase(),returnUrl:one("return_url"),webhookUrl:one("webhook_url"),signature:one("signature")};const payload=await post("/api/payments/izipay/form-session",checkout);const session:IzipayFormSession={formToken:text(payload.formToken),publicKey:text(payload.publicKey),resultUrl:text(payload.resultUrl),paymentScriptUrl:text(payload.paymentScriptUrl),themeScriptUrl:text(payload.themeScriptUrl),themeStylesheetUrl:text(payload.themeStylesheetUrl)};if(!session.formToken||!session.publicKey||!session.resultUrl||!session.paymentScriptUrl||!session.themeScriptUrl||!session.themeStylesheetUrl)throw new PaymentApiError("Rumbo API devolvió una sesión Izipay incompleta.",502);return{checkout,session}}
export async function processIzipayCallback(answerRaw:string,hash:string):Promise<PaymentEvent>{const payload=await post("/api/payments/izipay/callback",{answer_raw:answerRaw,hash});const status=text(payload.status) as PaymentEvent["status"],event:PaymentEvent={event_id:text(payload.event_id),event_type:text(payload.event_type),booking_reference:text(payload.booking_reference),provider_payment_id:text(payload.provider_payment_id),status,amount:text(payload.amount),currency:text(payload.currency)};if(!event.event_id||!event.event_type||!event.booking_reference||!event.provider_payment_id||!["pending","paid","failed","cancelled","refunded"].includes(status)||!event.amount||!event.currency)throw new PaymentApiError("Rumbo API devolvió un evento de pago incompleto.",502);return event}
