import { NextRequest, NextResponse } from "next/server";
import { accessConfiguration, backendMessage, fetchRumboApi, parseJson } from "../../../lib/rumbo-access";
import { PriceTravelError, searchPriceTravelPackages } from "../../../lib/pricetravel-packages";
import type { TravelPackage } from "../../../lib/travel-packages";

export const dynamic="force-dynamic";
const IATA_CODE=/^[A-Z]{3}$/,ISO_DATE=/^\d{4}-\d{2}-\d{2}$/,FLEX_DAYS=3;
type NativeDeparture={id:string;origin_iata?:string|null;departure_date?:string|null;return_date?:string|null;currency?:string;price_amount?:number;capacity?:number|null;available_capacity?:number|null;low_stock_threshold?:number|null;sale_deadline?:string|null;sale_open?:boolean;min_passengers_per_booking?:number;max_passengers_per_booking?:number;confirmation_mode?:"confirmed"|"minimum_required";minimum_group_size?:number|null;confirmation_label?:string};
type NativeProduct={id:string;slug:string;name:string;country?:string;city?:string;destination_iata?:string;duration_label?:string;tag?:string;included?:string[];image_url?:string;from_price_amount?:number;active_departure_count?:number;departures?:NativeDeparture[]};
const money=(amount:number,currency:string)=>new Intl.NumberFormat("es-PE",{style:"currency",currency,maximumFractionDigits:0}).format(amount);
const dayDiff=(a:string,b:string)=>Math.round(Math.abs(Date.parse(a)-Date.parse(b))/86_400_000);
function chooseDeparture(product:NativeProduct,input:{originIata:string;departureDate:string;returnDate:string;adults:number}){return(Array.isArray(product.departures)?product.departures:[]).filter(d=>{if(!d.id||!d.departure_date||!d.return_date)return false;if(d.origin_iata&&d.origin_iata!==input.originIata)return false;if(d.sale_open===false)return false;if(d.sale_deadline&&Date.parse(d.sale_deadline)<Date.now())return false;if(dayDiff(d.departure_date,input.departureDate)>FLEX_DAYS||dayDiff(d.return_date,input.returnDate)>FLEX_DAYS)return false;const min=Number(d.min_passengers_per_booking||1),max=Number(d.max_passengers_per_booking||9);if(input.adults<min||input.adults>max)return false;return d.available_capacity==null||d.available_capacity>=input.adults}).sort((a,b)=>{const ad=dayDiff(a.departure_date!,input.departureDate)+dayDiff(a.return_date!,input.returnDate),bd=dayDiff(b.departure_date!,input.departureDate)+dayDiff(b.return_date!,input.returnDate);return ad!==bd?ad-bd:Number(a.price_amount||0)-Number(b.price_amount||0)})[0]}
function nativePackage(product:NativeProduct,departure:NativeDeparture):TravelPackage{const amount=Number(departure.price_amount||0),fromAmount=Number(product.from_price_amount||amount),currency=departure.currency||"USD",remaining=departure.available_capacity??departure.capacity??undefined,threshold=departure.low_stock_threshold??5,lowStock=typeof remaining==="number"&&remaining>0&&remaining<=threshold,multiple=Number(product.active_departure_count||0)>1,confirmationLabel=departure.confirmation_label||(departure.confirmation_mode==="minimum_required"?"Sujeta a mínimo de pasajeros":"Salida confirmada");return{id:product.slug,destination:product.name,country:product.country||product.city||"",image:product.image_url||"/images/rumbo-hero.jpg",imagePosition:"center",duration:product.duration_label||"Consultar duración",rating:confirmationLabel,reviews:multiple?`${product.active_departure_count} salidas`:"Rumbo",price:multiple&&fromAmount>0?`Desde ${money(fromAmount,currency)}`:amount>0?money(amount,currency):"Consultar",previousPrice:"",tag:lowStock?`Últimos ${remaining} cupos`:confirmationLabel,included:Array.isArray(product.included)?product.included:[],capacity:remaining,departureDate:departure.departure_date||undefined,returnDate:departure.return_date||undefined,priceAmount:amount||undefined,currency,bookable:Boolean(departure.id&&amount>0&&departure.sale_open!==false&&(remaining==null||remaining>0)),variantId:departure.id,provider:"Rumbo",providerReference:`rumbo:${product.id}`,originIata:departure.origin_iata||undefined,lowStock,activeDepartureCount:Number(product.active_departure_count||0)}}
async function searchNativeCatalog(input:{originIata:string;destinationIata:string;departureDate:string;returnDate:string;adults:number}){const provider=accessConfiguration();if(!provider)throw new Error("Rumbo API no está configurada.");const response=await fetchRumboApi(provider,`/api/catalog?destination=${encodeURIComponent(input.destinationIata)}`);const payload=await parseJson(response) as {products?:NativeProduct[]};if(!response.ok||!Array.isArray(payload.products))throw new Error(backendMessage(payload as Record<string,unknown>,`Rumbo API devolvió HTTP ${response.status}.`));return payload.products.filter(p=>p.destination_iata===input.destinationIata).map(product=>({product,departure:chooseDeparture(product,input)})).filter((entry):entry is {product:NativeProduct;departure:NativeDeparture}=>Boolean(entry.departure)).map(({product,departure})=>nativePackage(product,departure))}

export async function GET(request:NextRequest){
 const p=request.nextUrl.searchParams,originIata=(p.get("origin")||"").toUpperCase(),destinationIata=(p.get("destination")||"").toUpperCase(),destinationName=(p.get("destinationName")||destinationIata).trim().slice(0,100),departureDate=p.get("departureDate")||"",returnDate=p.get("returnDate")||"",adults=Number(p.get("adults")||"2");
 if(!IATA_CODE.test(originIata)||!IATA_CODE.test(destinationIata)||!ISO_DATE.test(departureDate)||!ISO_DATE.test(returnDate)||!Number.isInteger(adults)||adults<1||adults>18||Date.parse(returnDate)<=Date.parse(departureDate))return NextResponse.json({mode:"error",provider:"Rumbo",packages:[],message:"Selecciona aeropuertos válidos, fechas consecutivas y entre 1 y 18 viajeros."},{status:400});
 let nativeError="";
 try{
  const native=await searchNativeCatalog({originIata,destinationIata,departureDate,returnDate,adults});
  if(native.length)return NextResponse.json({mode:"live",provider:"Rumbo",packages:native,message:`Encontramos ${native.length} opción${native.length===1?"":"es"} propia${native.length===1?"":"s"} de Rumbo para ${destinationName}, considerando hasta ±${FLEX_DAYS} días.`},{headers:{"Cache-Control":"private, max-age=15"}});
 }catch(error){nativeError=error instanceof Error?error.message:"El catálogo propio no respondió."}
 try{
  const result=await searchPriceTravelPackages({originIata,destinationIata,destinationName,departureDate,returnDate,adults,currency:"USD"});
  const prefix=nativeError?`El catálogo propio de Rumbo no respondió temporalmente. `:`No encontramos una salida propia de Rumbo dentro de ±${FLEX_DAYS} días. `;
  return NextResponse.json({...result,message:`${prefix}${result.message}`},{headers:{"Cache-Control":"private, max-age=30"}});
 }catch(error){
  if(error instanceof PriceTravelError){const detail=nativeError?`Catálogo Rumbo: ${nativeError}. PriceTravel: ${error.message}`:`No hay inventario propio compatible y PriceTravel falló: ${error.message}`;return NextResponse.json({mode:"error",provider:"PriceTravel",packages:[],message:detail},{status:error.status,headers:{"Cache-Control":"no-store"}})}
  return NextResponse.json({mode:"error",provider:"Rumbo",packages:[],message:nativeError|| (error instanceof Error?error.message:"No pudimos completar la búsqueda.")},{status:502,headers:{"Cache-Control":"no-store"}})
 }
}
